# Generated by Django 4.2.25 on 2025-12-07 03:00

from django.db import migrations
from globals.models.Categories import Categories
from globals.models.CategoryMedia import CategoryMedia

def load_initial_data(apps, schema_editor):
    if hasattr(Categories, "INITIAL_DATA"):
        initial_data = getattr(Categories, "INITIAL_DATA")

        # Insert/Update initial data rows
        for row in initial_data:
            # Ensure ID is used separately
            row_id = row.get("id")
            defaults = {k: v for k, v in row.items() if k != "id"}

            Categories.objects.get_or_create(id=row_id, defaults=defaults)

        if hasattr(CategoryMedia, "INITIAL_DATA"):
            initial_data = getattr(CategoryMedia, "INITIAL_DATA")
            # Insert/Update initial data rows
            for row in initial_data:
                # Ensure ID is used separately
                row_id = row.get("id")
                defaults = {k: v for k, v in row.items() if k != "id"}

                CategoryMedia.objects.get_or_create(id=row_id, defaults=defaults)



class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(load_initial_data),
    ]
