# Generated by Django 4.2.27 on 2025-12-10 14:01

from django.db import migrations

def load_initial_data(apps, schema_editor):
    from django.apps import apps as global_apps

    # Iterate through all registered models
    for model in global_apps.get_models():
        if model._meta.model_name == "categories":
            continue
        # Only process models having INITIAL_DATA attribute
        if hasattr(model, "INITIAL_DATA"):
            initial_data = getattr(model, "INITIAL_DATA")

            # Insert/Update initial data rows
            for row in initial_data:
                # Ensure ID is used separately
                row_id = row.get("id")
                defaults = {k: v for k, v in row.items() if k != "id"}

                model.objects.get_or_create(
                    id=row_id, defaults=defaults
                )
class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_initial_data),
    ]
