"""
Django settings for ndf project.

Generated by 'django-admin startproject' using Django 4.2.27.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
from django.forms.renderers import TemplatesSetting

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-wh9cn^d2a@*s!vcp4y#1tip_yokdxbd=wc*h!c)(#f-!o(@c^h'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['13.205.19.22','127.0.0.1','newdecorfurnishing.com','www.newdecorfurnishing.com']

CSRF_TRUSTED_ORIGINS = [
    "https://newdecorfurnishing.com",
    "https://www.newdecorfurnishing.com",
]

# Application definition

INSTALLED_APPS = [
    "common.apps.CommonConfig",
    "globals.apps.GlobalsConfig",
    "banners.apps.BannersConfig",
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

JAZZMIN_SETTINGS = {
    
    "welcome_sign": "Welcome to New Decor Furnishing",
    "show_sidebar": True,
    "navigation_expanded": False,
    "show_ui_builder": True,

    "site_title": "New Decor Furnishing Admin",
    "site_header": "New Decor Furnishing",
    "site_logo": "frontend/assets/images/logo5.png",  # Relative to STATIC_URL
    "site_logo_classes": " bg-white",  # Optional
    "login_logo": "frontend/assets/images/logo5.png",       # Login page logo
    "login_logo_dark": "frontend/assets/images/logo5.png",  # Dark mode logo

    # Optional
    "site_brand": "NDF",
    
}

JAZZMIN_UI_TWEAKS = {

    "navbar_small_text": False,

    "footer_small_text": False,

    "body_small_text": False,

    "brand_small_text": False,

    "brand_colour": False,

    "accent": "accent-primary",

    "navbar": "navbar-white navbar-light",

    "no_navbar_border": False,

    "navbar_fixed": False,

    "layout_boxed": False,

    "footer_fixed": False,

    "sidebar_fixed": False,

    "sidebar": "sidebar-dark-primary",

    "sidebar_nav_small_text": False,

    "sidebar_disable_expand": False,

    "sidebar_nav_child_indent": True,

    "sidebar_nav_compact_style": False,

    "sidebar_nav_legacy_style": False,

    "sidebar_nav_flat_style": False,

    "theme": "default",

    "dark_mode_theme": None,

    "button_classes": {

        "primary": "btn-primary",

        "secondary": "btn-secondary",

        "info": "btn-info",

        "warning": "btn-warning",

        "danger": "btn-danger",

        "success": "btn-success"

    }

}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ndf.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        "DIRS": [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'globals.context_processors.categories_processor',
            ],
        },
    },
]

WSGI_APPLICATION = 'ndf.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
        'OPTIONS': {
            'timeout': 30,
        }
    }
}

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',  # MySQL engine
#         'NAME': 'ndf',          # Database name
#         'USER': 'root',             # MySQL username
#         'PASSWORD': 'root@123',     # MySQL password
#         'HOST': 'localhost',                   # Hostname (or IP)
#         'PORT': '3306',                        # Default MySQL port
#         'OPTIONS': {
#             'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
#         },
#     }
# }


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / "static",   # jaha aap manually static files likhte ho
]
STATIC_ROOT = BASE_DIR / "staticfiles"  # 👈 collectstatic inko yaha copy karega


# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# media files(uploaded images)

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

FORM_RENDERER = "ndf.settings.TemplatesSetting"